networks:
  ai_stack:

volumes:
  pg_data:

services:
  postgres:
    image: docker.artifactory.omnisys.local/pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [ai_stack]

  adminer:
    image: docker.artifactory.omnisys.local/library/adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks: [ai_stack]

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    volumes:
      - ../backend/app:/app/app
      - ../backend/alembic.ini:/app/alembic.ini
      - ../backend/alembic:/app/alembic
    env_file:
      - ./.env
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      LLM_CHAT_MODEL: ${LLM_CHAT_MODEL}
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    extra_hosts:
      - "Omniai:192.168.1.43"
    networks: [ai_stack]
